### ISSUE TITLE
Great use-case for openfaas

### ISSUE THREAD

**Issue by alexellis** [genebean/fbc-slackbot#5]
Hi Gene,

This is a great use-case for openfaas, I'd love to share it with the community.

Do you think you could add a README with deployment instructions, how to use it and a few links? As part of the Insiders Cove benefit, I'd be up for sharing it in this week's featured projects/links from Insiders.

Alex

**Comment by genebean** [comment]
Sharing it sounds awesome to me, I will work on this tonight or tomorrow night

**Comment by genebean** [comment]
I think I got everything documented but I have not had time to run through it fresh via the docs.
